# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoanApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LoanApp

    pod 'FirebaseAnalytics'
    pod 'Firebase/Messaging'

  target 'LoanApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FirebaseAnalytics'
    pod 'Firebase/Messaging'
  end

  target 'LoanAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FirebaseAnalytics'
    pod 'Firebase/Messaging'
  end

end

